### PR TITLE
Use Visual Studio 2019 image

### PR DESCRIPTION
**Pull request by jgsogo**
I think the image `Visual Studio 2019` is already available

### CODE REVIEW

**Comment by SSE4** [comment]
```
'vstest.console' is not recognized as an internal or external command,
operable program or batch file
```
what is this `vctest.console`?

**Comment by jgsogo** [comment]
Related: https://help.appveyor.com/discussions/problems/23916-visual-studio-2019-vstestconsole-not-found-loggerappveyor-not-found

It looks like it is something that the test project is using. Maybe it is not in the path of the non-preview images 🤷‍♂

**Comment by SSE4** [comment]
okay, let's wait for a while with this one then. I've just subscribed for notifications of appveyor ticker.

**Comment by jgsogo** [comment]
@SSE4 we have to assign every PR to a milestone before merging so we don't miss any change 👍

**Pull request merged**
