### PR TITLE
Fix vs2015

### LINKED ISSUE #66: [vs2015] Error loading in VS 2015
```
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [VSConanPackage]Source: &apos;mscorlib&apos; Description: Could not load file or assembly &apos;Microsoft.VisualStudio.Shell.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.VisualStudio.Shell.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Microsoft.VisualStudio.Shell.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)&#x000D;&#x000A;   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)&#x000D;&#x000A;   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
    <guid>{33315C89-72DD-43BB-863C-561C1AA5ED54}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo></errorinfo>
```

Maybe related: https://github.com/samizzo/nshader/issues/12
Also: https://github.com/StefanKert/BuildVision/issues/34

Note.- It has to be tested **in a machine with only 2015 installed** (other installations of VS in the same machine hide this error).

### PR DESCRIPTION
**Pull request by SSE4**
closes #66

### CODE REVIEW

**Comment by SSE4** [comment]
checked on VM with only VS2015 installed, works flawlessly

**Comment by Gernatch** [comment]
@jgsogo Do you think this will make it to 1.1? We have someone having this issue and I would like to see if this resolves. Or is there a VSIX I could supply with this change for testing?

**Comment by SSE4** [comment]
@Gernatch you may try to install from here: https://ci.appveyor.com/project/ConanOrgCI/conan-vs-extension/builds/25177464/artifacts
please let us know if it works for you

**Comment by Gernatch** [comment]
@SSE4 Hm. This actually doesn't work for me.
```
    <description>Client rights determined: {&quot;CurrentClientRights&quot;:{&quot;ActivityId&quot;:&quot;5210f107-241d-4d79-8eab-7b55ae79ab1c&quot;,&quot;AuthorizedVsEdition&quot;:2,&quot;AuthorizedVsEdition2&quot;:300,&quot;CrtokenDaysToExpire&quot;:30,&quot;DaysSinceCreation&quot;:0,&quot;DaysToExpire&quot;:30,&quot;IsLicenseGood&quot;:true,&quot;IsSubscriptionBased&quot;:true,&quot;IsTrialLicense&quot;:false,&quot;LicenseDescription&quot;:&quot;MSDN Subscription&quot;,&quot;LicensedUserId&quot;:&quot;ac88aa23-e23a-40f2-b1b4-4454e89428a0&quot;,&quot;LicensedUserName&quot;:&quot;username@company(edited this).com&quot;,&quot;LicenseSource&quot;:1,&quot;LicenseSource2&quot;:1,&quot;LicenseStatus&quot;:4,&quot;LicenseType&quot;:12,&quot;LicenseUrl&quot;:&quot;&quot;,&quot;LicensingAccount&quot;:&quot;&quot;,&quot;MayUplevel&quot;:false,&quot;ReleaseType&quot;:1,&quot;RightsDaysToExpire&quot;:2147483647,&quot;RightsStatus&quot;:10,&quot;SubscriptionChannel&quot;:&quot;VL&quot;,&quot;ClientRightsMetadata&quot;:{&quot;SubscriptionChannel&quot;:&quot;VL&quot;,&quot;NonLocalizedLicenseDescription&quot;:&quot;MSDN&quot;,&quot;LicenseUrl&quot;:&quot;&quot;,&quot;ExpirationDate&quot;:&quot;\/Date(1563371882000)\/&quot;,&quot;ClientRightsVersion&quot;:{&quot;Major&quot;:15,&quot;Minor&quot;:0,&quot;Build&quot;:28307,&quot;Revision&quot;:705,&quot;MajorRevision&quot;:0,&quot;MinorRevision&quot;:705}}},&quot;CurrentLicenseSource&quot;:1,&quot;CurrentLicenseSource2&quot;:1,&quot;IDEUserClientRights&quot;:{&quot;ActivityId&quot;:&quot;5210f107-241d-4d79-8eab-7b55ae79ab1c&quot;,&quot;AuthorizedVsEdition&quot;:2,&quot;AuthorizedVsEdition2&quot;:300,&quot;CrtokenDaysToExpire&quot;:30,&quot;DaysSinceCreation&quot;:0,&quot;DaysToExpire&quot;:30,&quot;IsLicenseGood&quot;:true,&quot;IsSubscriptionBased&quot;:true,&quot;IsTrialLicense&quot;:false,&quot;LicenseDescription&quot;:&quot;MSDN Subscription&quot;,&quot;LicensedUserId&quot;:&quot;ac88aa23-e23a-40f2-b1b4-4454e89428a0&quot;,&quot;LicensedUserName&quot;:&quot;username@company(edited this).com&quot;,&quot;LicenseSource&quot;:1,&quot;LicenseSource2&quot;:1,&quot;LicenseStatus&quot;:4,&quot;LicenseType&quot;:12,&quot;LicenseUrl&quot;:&quot;&quot;,&quot;LicensingAccount&quot;:&quot;&quot;,&quot;MayUplevel&quot;:false,&quot;ReleaseType&quot;:1,&quot;RightsDaysToExpire&quot;:2147483647,&quot;RightsStatus&quot;:10,&quot;SubscriptionChannel&quot;:&quot;VL&quot;,&quot;ClientRightsMetadata&quot;:{&quot;SubscriptionChannel&quot;:&quot;VL&quot;,&quot;NonLocalizedLicenseDescription&quot;:&quot;MSDN&quot;,&quot;LicenseUrl&quot;:&quot;&quot;,&quot;ExpirationDate&quot;:&quot;\/Date(1563371882000)\/&quot;,&quot;ClientRightsVersion&quot;:{&quot;Major&quot;:15,&quot;Minor&quot;:0,&quot;Build&quot;:28307,&quot;Revision&quot;:705,&quot;MajorRevision&quot;:0,&quot;MinorRevision&quot;:705}}},&quot;PIDClientRights&quot;:{&quot;LicenseSource&quot;:0,&quot;LicenseSource2&quot;:0,&quot;IsSubscriptionBased&quot;:false,&quot;DaysSinceCreation&quot;:-1,&quot;LicenseType&quot;:2,&quot;AuthorizedVsEdition&quot;:2,&quot;AuthorizedVsEdition2&quot;:300,&quot;DaysToExpire&quot;:-1,&quot;IsLicenseGood&quot;:false,&quot;LicenseDescription&quot;:&quot;30 day trial (for evaluation purposes only)&quot;,&quot;LicenseStatus&quot;:-1,&quot;LicenseUrl&quot;:&quot;&quot;,&quot;MayUplevel&quot;:false,&quot;LicensedUserId&quot;:&quot;00000000-0000-0000-0000-000000000000&quot;,&quot;LicensedUserName&quot;:&quot;&quot;,&quot;LicensingAccount&quot;:&quot;&quot;,&quot;ReleaseType&quot;:1}}; Account identity provider: AAD</description>
```

**Comment by SSE4** [comment]
a bit beautified output:
```
    <description>Client rights determined: {"CurrentClientRights":{"ActivityId":"5210f107-241d-4d79-8eab-7b55ae79ab1c","AuthorizedVsEdition":2,"AuthorizedVsEdition2":300,"CrtokenDaysToExpire":30,"DaysSinceCreation":0,"DaysToExpire":30,"IsLicenseGood":true,"IsSubscriptionBased":true,"IsTrialLicense":false,"LicenseDescription":"MSDN Subscription","LicensedUserId":"ac88aa23-e23a-40f2-b1b4-4454e89428a0","LicensedUserName":"username@company(edited this).com","LicenseSource":1,"LicenseSource2":1,"LicenseStatus":4,"LicenseType":12,"LicenseUrl":"","LicensingAccount":"","MayUplevel":false,"ReleaseType":1,"RightsDaysToExpire":2147483647,"RightsStatus":10,"SubscriptionChannel":"VL","ClientRightsMetadata":{"SubscriptionChannel":"VL","NonLocalizedLicenseDescription":"MSDN","LicenseUrl":"","ExpirationDate":"\/Date(1563371882000)\/","ClientRightsVersion":{"Major":15,"Minor":0,"Build":28307,"Revision":705,"MajorRevision":0,"MinorRevision":705}}},"CurrentLicenseSource":1,"CurrentLicenseSource2":1,"IDEUserClientRights":{"ActivityId":"5210f107-241d-4d79-8eab-7b55ae79ab1c","AuthorizedVsEdition":2,"AuthorizedVsEdition2":300,"CrtokenDaysToExpire":30,"DaysSinceCreation":0,"DaysToExpire":30,"IsLicenseGood":true,"IsSubscriptionBased":true,"IsTrialLicense":false,"LicenseDescription":"MSDN Subscription","LicensedUserId":"ac88aa23-e23a-40f2-b1b4-4454e89428a0","LicensedUserName":"username@company(edited this).com","LicenseSource":1,"LicenseSource2":1,"LicenseStatus":4,"LicenseType":12,"LicenseUrl":"","LicensingAccount":"","MayUplevel":false,"ReleaseType":1,"RightsDaysToExpire":2147483647,"RightsStatus":10,"SubscriptionChannel":"VL","ClientRightsMetadata":{"SubscriptionChannel":"VL","NonLocalizedLicenseDescription":"MSDN","LicenseUrl":"","ExpirationDate":"\/Date(1563371882000)\/","ClientRightsVersion":{"Major":15,"Minor":0,"Build":28307,"Revision":705,"MajorRevision":0,"MinorRevision":705}}},"PIDClientRights":{"LicenseSource":0,"LicenseSource2":0,"IsSubscriptionBased":false,"DaysSinceCreation":-1,"LicenseType":2,"AuthorizedVsEdition":2,"AuthorizedVsEdition2":300,"DaysToExpire":-1,"IsLicenseGood":false,"LicenseDescription":"30 day trial (for evaluation purposes only)","LicenseStatus":-1,"LicenseUrl":"","MayUplevel":false,"LicensedUserId":"00000000-0000-0000-0000-000000000000","LicensedUserName":"","LicensingAccount":"","ReleaseType":1}}; Account identity provider: AAD</description>
```

**Comment by Gernatch** [comment]
@SSE4 I tried to delete my reply. Wasn't quick enough. Somehow my VS key became deactivated... or I was switched to a 30day MSDN subscription without realizing it. Sorry for the confusion. 

I am seeing the netstandard error that was fixed on PR #89. That is the real cause of the issue. I assume this will be a non issue when this is all merged together.

**Comment by SSE4** [comment]
@Gernatch so to confirm, does it work for you with just #89 applied, or only with both #89 + #75?

**Comment by Gernatch** [comment]
@SSE4 I install the #89 using the VSIX, it works. I do the same for #75, it does not. Note again I'm running a VS2017 version.

**Comment by jgsogo** [comment]
So, you are not blocked by this PR which is targeting VS2015, right?

I think we can release `v1.1` (main change is #89) this week and leave #85 for the next one (it is one of the major/breaking changes I think we need to implement asap).

**Comment by kkripa84** [comment]
@SSE4 I see issues with this extension when I installed in VS2017 15.0.0 +26228.57 version.

image

After install, I clicked continue with the error message

Error I see  in my activitylog

Could not load file or assembly &apos;Microsoft.VisualStudio.Threading, Version=15.6.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &
 
Assembly binding logging is turned OFF.&#x000D;&#x000A;

**Comment by jgsogo** [comment]
@SSE4, can you merge `dev`, please. We will try to merge this for `v1.1` too. Thanks

**Comment by SSE4** [comment]
@jgsogo done

**Comment by jgsogo** [comment]
Thanks! I'll test it in clean Windows + VS2015 installation. If anyone else wants to try, here it is the link to the artifact: https://ci.appveyor.com/api/buildjobs/0ch7aaf8wak0ngym/artifacts/Conan.VisualStudio%2Fbin%2FRelease%2FConan.VisualStudio.vsix

**Comment by jgsogo** [comment]
Tested with:
 * VS 2015 Community Update 3, installed in a VM from scratch only with Visual C++. It works 👌 
 * VS 2019, it doesn't run 😞

**Comment by Gernatch** [comment]
Kripa (above) tried installing this today. It seems like it loaded, but all functionality seems to be disabled. @kkripa84 is that right?

**Comment by jgsogo** [comment]
This fails casting the `Project` to a `VCProject` (we need to convert it to a C++ type project to get its configuration and so). The VCProject relies on the `VCProjectEngine.dll` which is different from version to version (at least I found them to be incompatible between 14 and 16, which is the change needed from VS2015 to VS2019).

There are some ideas to follow:
 * Check against the UUID: https://github.com/VioletGiraffe/cppcheck-vs-addin/issues/156 Not useful here, we not only to know it is a C++ project, but also we need to d the actual cast to retrieve its properties
 * Here they suggest different extensions for different VS versions: https://stackoverflow.com/questions/44288050/typecast-fails-when-visual-studio-extension-uses-reference-to-older-assembly
 * The most promising one (to ensure compatibility now and then) is to split the Extension into different assemblies, so we keep the logic in a single one and build different assemblies for each VS version: http://www.visualstudioextensibility.com/2014/07/01/strategies-migrating-from-visual-studio-add-ins-to-packages/

**Comment by jgsogo** [comment]
> Kripa (above) tried installing this today. It seems like it loaded, but all functionality seems to be disabled. @kkripa84 is that right?

Hi @Gernatch  the problem here is summarized in [this post from the MSFT team](https://developercommunity.visualstudio.com/content/problem/568/systeminvalidcastexception-unable-to-cast-com-obje.html), we cannot have a single extension compatible with VS2015 and VS2017/9 (at least using the current approach).

**Comment by LBHawk** [comment]
To clarify, we (myself, @Gernatch, @kkripa84) are not blocked by this PR for vs2015.  I think we should keep the vs2017 issues we have (which _are_ blocking for us) separate from this PR.

**Pull request closed without merging**
