### PR TITLE
add .vsconfig

### LINKED ISSUE #86: document developer set up
need to document (in the README.MD or CONTRIBUTE.MD) how to prepare developer set up, with check boxes to check in Visual Studio installer, may be with screen-shots or GIFs.

### PR DESCRIPTION
**Pull request by SSE4**
closes #86

### CODE REVIEW

**Comment by jgsogo** [comment]
Please, add it to the documentation, to the README page. I think it is useful to add a picture  to let the developer know how to start with this project

I copy you an image you can use (VS 2019)

image

**Comment by SSE4** [comment]
added

**Comment by jgsogo** [comment]
I've tried removing all the components from my VS installation, then opening the solution and installing the suggested packages. I found some issue with the packages cached by NuGet, but nothing related to the extension. I've needed to restore NuGet cache, open/close Visual Studio,... but at the end everything works without changing a line.

Anyway, I get some warnings:

```

```

**Comment by SSE4** [comment]
default build is "treat warnings as errors". does it build for you with these warnings?
anyway, these assemblies are from 16.0 (VS 2019), but we're not referencing them everywhere. I believe it should be safe to ignore.

**Comment by jgsogo** [comment]
It works! Created issue https://github.com/conan-io/conan-vs-extension/issues/93 and merging this one. Thanks!

**Pull request merged**
